export const CHANGE_SIZE_TYPE = "CHANGE_SIZE_TYPE";
export const OPEN_MENU_TYPE = "OPEN_MENU_TYPE";
export const CLOSE_MENU_TYPE = "CLOSE_MENU_TYPE";
export const SELECT_LANGUAGE_TYPE = "SELECT_LANGUAGE_TYPE";
export const SELECT_TECHNOLOGY_TYPE = "SELECT_TECHNOLOGY_TYPE";
export const RESET_TECHNOLOGY_TYPE = "RESET_TECHNOLOGY_TYPE";
export const OPEN_TECHNOLOGY_INFO_TYPE = "OPEN_TECHNOLOGY_INFO_TYPE";
export const CLOSE_TECHNOLOGY_INFO_TYPE = "CLOSE_TECHNOLOGY_INFO_TYPE";
